# Generated by Django 6.0.5 on 2026-06-12 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0009_stockmovement"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to="products/"),
        ),
    ]
